FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Program.bf", "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\Attribute.bf", "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\Compiler.bf", "src\\Types.bf", "src\\Win32\\LibraryLoader.bf", "src\\Win32\\Foundation.bf", "src\\Steam\\SteamAPI.bf"]

[MainWindow]
X = 4507
Y = 63
Width = 600
Height = 446
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 2558.0
RequestedHeight = 440.0
SizePriority = 0.6057839
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 2161.52
RequestedHeight = 1041.52
SizePriority = 1041.52
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 417.6
RequestedHeight = 1331.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.0968
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 2161.52
RequestedHeight = 150.0
SizePriority = 2161.52
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 102.4194
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 7710
VertPos = 2945.0
ProjectName = "RfgNetworkAPI"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Types.bf"
TabWidth = 84.67742
Type = "SourceViewPanel"
FilePath = "src\\Types.bf"
CursorPos = 295
ProjectName = "RfgNetworkAPI"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SteamAPI.bf"
TabWidth = 107.2581
Type = "SourceViewPanel"
FilePath = "src\\Steam\\SteamAPI.bf"
CursorPos = 418
ProjectName = "RfgNetworkAPI"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "LibraryLoader.bf"
TabWidth = 130.6452
Type = "SourceViewPanel"
FilePath = "src\\Win32\\LibraryLoader.bf"
CursorPos = 82
VertPos = 19.0
ProjectName = "RfgNetworkAPI"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Foundation.bf"
TabWidth = 116.9355
Type = "SourceViewPanel"
FilePath = "src\\Win32\\Foundation.bf"
CursorPos = 141
ProjectName = "RfgNetworkAPI"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Compiler.bf"
TabWidth = 104.0323
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\Compiler.bf"
CursorPos = 6317
VertPos = 4313.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 287.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4589523
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 76.6129
Type = "AutoWatchPanel"
Columns = [{Width = 288.0}, {Width = 1409.0}, {Width = 288.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.48387
Type = "WatchPanel"
Columns = [{Width = 288.0}, {Width = 288.0}, {Width = 288.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.35484
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 98.38709
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.58064
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 83.87096
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 2233.52
RequestedHeight = 250.0
SizePriority = 0.4589523
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 89.51613
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.0323
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.6774
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 117.7419
Type = "FindResultsPanel"

[[BookmarkFolders]]
Title = ""
