FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win32"
RecentFilesList = ["src\\Program.bf", "src\\Backend\\Debug\\DebugBackend.bf", "src\\Backend\\Community\\CommunityBackend.bf", "src\\API\\SteamAPI.bf", "src\\Backend\\Community\\CNetworking.bf", "src\\Backend\\BackendData.bf", "dependencies\\bon\\src\\BonSetup.bf", "Disassembly", "src\\Backend\\Community\\CUser.bf", "src\\Backend\\Community\\CFriends.bf", "src\\Backend\\Community\\CApps.bf", "src\\Backend\\Community\\CMatchmaking.bf", "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\Result.bf", "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\StreamWriter.bf", "src\\Misc\\Logger.bf", "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefRT\\rt\\Internal.cpp", "src\\Misc\\Helpers.bf", "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\BufferedStream.bf", "src\\Backend\\Community\\CClient.bf", "src\\Backend\\Shim\\ShimBackend.bf"]

[MainWindow]
X = 1956
Y = 0
Width = 604
Height = 453
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 2558.0
RequestedHeight = 440.0
SizePriority = 2558.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 2161.52
RequestedHeight = 1090.52
SizePriority = 1090.52
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 585.0
RequestedHeight = 1331.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 114.0351
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 2047.52
RequestedHeight = 1090.52
SizePriority = 2047.52
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 94.91233
TabIsPinned = true
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 1021
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "DebugBackend.bf"
TabWidth = 133.5089
TabIsPinned = true
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Debug\\DebugBackend.bf"
CursorPos = 344
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CommunityBackend.bf"
TabWidth = 160.7019
TabIsPinned = true
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CommunityBackend.bf"
CursorPos = 196
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BackendData.bf"
TabWidth = 122.1053
TabIsPinned = true
Type = "SourceViewPanel"
FilePath = "src\\Backend\\BackendData.bf"
CursorPos = 13133
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BonSetup.bf"
TabWidth = 101.0527
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "dependencies\\bon\\src\\BonSetup.bf"
CursorPos = 668
ProjectName = "bon"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StreamWriter.bf"
TabWidth = 121.2281
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\StreamWriter.bf"
CursorPos = 2012
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Result.bf"
TabWidth = 80.00004
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\Result.bf"
CursorPos = 1763
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "SteamAPI.bf"
TabWidth = 101.0527
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\API\\SteamAPI.bf"
CursorPos = 34714
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 121.9299
TabIsPinned = false
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "BufferedStream.bf"
TabWidth = 136.1404
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\BufferedStream.bf"
CursorPos = 2342
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Path.bf"
TabWidth = 70.35091
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\Path.bf"
CursorPos = 11209
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Internal.cpp"
TabWidth = 98.4211
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefRT\\rt\\Internal.cpp"
CursorPos = 11396

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "HashCode.bf"
TabWidth = 104.5615
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\HashCode.bf"
CursorPos = 2974
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Extensions.bf"
TabWidth = 105.4387
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Misc\\Extensions.bf"
CursorPos = 1530
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 79.12285
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 26605
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "FileStream.bf"
TabWidth = 106.3158
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\FileStream.bf"
CursorPos = 10925
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CClient.bf"
TabWidth = 86.1404
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CClient.bf"
CursorPos = 2759
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CFriends.bf"
TabWidth = 94.03514
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CFriends.bf"
CursorPos = 5753
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CUtils.bf"
TabWidth = 78.24565
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CUtils.bf"
CursorPos = 3968
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CNetworking.bf"
TabWidth = 120.351
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CNetworking.bf"
CursorPos = 2849
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CUser.bf"
TabWidth = 77.36845
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CUser.bf"
CursorPos = 1588
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CMatchmaking.bf"
TabWidth = 131.7545
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CMatchmaking.bf"
CursorPos = 5651
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CApps.bf"
TabWidth = 82.63162
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CApps.bf"
CursorPos = 4481
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CRemoteStorage.bf"
TabWidth = 144.0352
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CRemoteStorage.bf"
CursorPos = 18500
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CUserStats.bf"
TabWidth = 106.3158
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CUserStats.bf"
CursorPos = 3373
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CController.bf"
TabWidth = 109.8246
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Community\\CController.bf"
CursorPos = 2767
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Helpers.bf"
TabWidth = 89.64917
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Misc\\Helpers.bf"
CursorPos = 8135
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Logger.bf"
TabWidth = 85.2632
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Misc\\Logger.bf"
CursorPos = 1259
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "LogWrappers.bf"
TabWidth = 122.9825
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Backend\\Debug\\LogWrappers.bf"
CursorPos = 9244
ProjectName = "RfgNetworking"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 306.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.4589523
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 78.0702
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 288.0}, {Width = 1409.0}, {Width = 288.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Watch"
TabWidth = 86.84214
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 288.0}, {Width = 288.0}, {Width = 288.0}]
Items = ["_originalVtable", "RemoteStorageFolder", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 95.61407
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 100.0
TabIsPinned = false
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 98.24566
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 83.33337
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Diagnostics"
TabWidth = 117.5439
TabIsPinned = false
Type = "DiagnosticsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 2233.52
RequestedHeight = 250.0
SizePriority = 0.4589523
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.35091
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 106.1404
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 113.158
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 118.4211
TabIsPinned = false
Type = "FindResultsPanel"

[[Breakpoints]]
File = "src\\Backend\\Community\\CommunityBackend.bf"
Line = 143
Column = 8

[[Breakpoints]]
File = "src\\Backend\\Community\\CommunityBackend.bf"
Line = 148
Column = 8

[[Breakpoints]]
File = "src\\Backend\\Community\\CommunityBackend.bf"
Line = 128
Column = 8

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 146
Column = 12

[[Breakpoints]]
File = "src\\Program.bf"
Line = 74
Column = 12
Disabled = true

[[Breakpoints]]
File = "src\\Program.bf"
Line = 80
Column = 12

[[Breakpoints]]
File = "src\\Program.bf"
Line = 98
Column = 12

[[Breakpoints]]
File = "src\\Backend\\Debug\\DebugBackend.bf"
Line = 331
Column = 8

[[Breakpoints]]
File = "src\\Backend\\Debug\\DebugBackend.bf"
Line = 336
Column = 8

[[Breakpoints]]
File = "src\\Backend\\Debug\\DebugBackend.bf"
Line = 331
Column = 8

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 272
Column = 12

[[Breakpoints]]
File = "src\\Backend\\Debug\\LogWrappers.bf"
Line = 228
Column = 16

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 278
Column = 12
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 278
Column = 12
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 287
Column = 12
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 297
Column = 16
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 297
Column = 16
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 297
Column = 16
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 297
Column = 16
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 320
Column = 16

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 260
Column = 12

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 302
Column = 16
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 302
Column = 16
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 306
Column = 16
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 278
Column = 12
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 144
Column = 12

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 144
Column = 12

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 226
Column = 12

[[Breakpoints]]
File = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\BufferedStream.bf"
Line = 73
Column = 4

[[Breakpoints]]
File = "c:\\Users\\lukem\\source\\repos\\_DownloadedRepos\\Beef\\BeefLibs\\corlib\\src\\IO\\BufferedStream.bf"
Line = 69
Column = 3

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 141
Column = 20
Disabled = true

[[Breakpoints]]
File = "src\\Backend\\Community\\CRemoteStorage.bf"
Line = 137
Column = 24

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
