FileVersion = 1

[Project]
Name = "RfgNetworkAPI"
TargetType = "BeefLib"
StartupObject = "RfgNetworkAPI.Program"

[Configs.Debug.Win32]
BuildKind = "DynamicLib"

[Configs.Debug.Win64]
BuildKind = "DynamicLib"

[Configs.Release.Win32]
BuildKind = "DynamicLib"

[Configs.Release.Win64]
BuildKind = "DynamicLib"

[Configs.Paranoid.Win32]
BuildKind = "DynamicLib"

[Configs.Paranoid.Win64]
BuildKind = "DynamicLib"

[Configs.Test.Win32]
BuildKind = "DynamicLib"

[Configs.Test.Win64]
BuildKind = "DynamicLib"
