FileVersion = 1
Dependencies = {corlib = "*", bon = "*"}

[Project]
Name = "RfgNetworking"
TargetType = "BeefLib"
StartupObject = "RfgNetworking.Program"

[Configs.Debug.Win32]
BuildKind = "DynamicLib"
TargetName = "sw_api"
BeefLibType = "DynamicDebug"
PostBuildCmds = ["CopyFilesIfNewer(\"$(BuildDir)/sw_api.dll\", \"D:/GOG/Games/Red Faction Guerrilla Re-Mars-tered/\")"]
DebugCommand = "D:/GOG/Games/Red Faction Guerrilla Re-Mars-tered/Launcher.exe"
DebugWorkingDirectory = "d:\\GOG\\Games\\Red Faction Guerrilla Re-Mars-tered\\"

[Configs.Debug.Win64]
BuildKind = "DynamicLib"
TargetName = "sw_api"
BeefLibType = "Static"

[Configs.Paranoid.Win32]
BuildKind = "DynamicLib"
TargetName = "sw_api"

[Configs.Paranoid.Win64]
BuildKind = "DynamicLib"
TargetName = "sw_api"

[Configs.Release.Win32]
BuildKind = "DynamicLib"
TargetName = "sw_api"

[Configs.Release.Win64]
BuildKind = "DynamicLib"
TargetName = "sw_api"

[Configs.Test.Win32]
BuildKind = "DynamicLib"
TargetName = "sw_api"

[Configs.Test.Win64]
BuildKind = "DynamicLib"
TargetName = "sw_api"
